<a href="https://colab.research.google.com/github/ghozieikhsanf/Pemrograman-Python/blob/main/Ghozie_Ikhsan_Fairuz1101174489_week11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/MyDrive/Set Data

/content/drive/MyDrive/Set Data


In [4]:
ls

3scene/  best_weight_scene_mobileNet.h5  dataset/  milkyway.jpg  nnmodel_scene/


In [5]:
# Import necessary modules and packages
from keras.models import Sequential
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image
from imutils import paths
import numpy as np
import os

In [6]:
# Create the image path with "paths" in the input data dataset directory
# List the images and its labels
print("[INFO] loading images..")
imagePaths = paths.list_images("dataset")
data = []
labels = []

[INFO] loading images..


In [7]:
# Loop over the input images using "for" function:
for imagePath in imagePaths:
  # Load the input image from the selected image path
  image = Image.open(imagePath)

  # Resize it to 64x64 pixels, the pixel intensities to the range [0,1] and then updateour image list
  # Conducting the prepocessing and normalize process to the image
  image = np.array(image.resize((64,64))) / 255.0 
  data.append(image)

  # Extract the class label from the path file and update the labels list
  label = imagePath.split(os.path.sep)[-2]
  labels.append(label)

In [8]:
# Visualize the input image label list
print(labels)


['nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB', 'nonGMB',

In [9]:
# Encode the input image labels, convert them from strings to integers to make easier for computer to proceed
lb = LabelBinarizer()
labels = lb.fit_transform(labels)

In [10]:
# Visualize the converted input label images
print(labels)

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [11]:
# Perform a training and testing split data for modeling
# Using 75% of the data for training and 25% of the data for evaluation
(trainX, testX, trainY, testY) = train_test_split(np.array(data), np.array(labels), test_size=0.25, shuffle=True)

# Visualize train and test X shape
print(trainX.shape)
print(testX.shape)

(1055, 64, 64, 3)
(352, 64, 64, 3)


In [12]:
# Conducting Convolutional Neural Network and Fully Connected Feedforward Network

# Import necessary modules and packages
from keras.layers import Convolution2D, MaxPooling2D
from keras.models import Sequential
from keras.layers.core import Flatten, Dense

# Proceed the CNN stages (2 times of Convolution and Max Pooling)
model = Sequential()
model.add(Convolution2D(8, (3,3), activation='relu', input_shape=(64,64,3)))
model.add(MaxPooling2D(2,2))
model.add(Convolution2D(16, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

# Conduct the Fully Connected Layer stages
model.add(Flatten()) # remap the weight to 1D
model.add(Dense(100, activation='relu'))
model.add(Dense(5, activation='softmax')) # 5 for attributes that is use for this modeling

# Perform the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 8)         224       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 8)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 29, 29, 16)        1168      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
flatten (Flatten)            (None, 3136)              0         
_________________________________________________________________
dense (Dense)                (None, 100)               313700    
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 5

In [21]:
# train the model using the Adam optimizer
print("[INFO] training network...")
opt = Adam(lr=1e+3, decay=1e+3 / 10)
model.compile(loss="categorical_crossentropy", optimizer=opt,
	metrics=["accuracy"])
H = model.fit(trainX, trainY, validation_data=(testX, testY), epochs=21, batch_size=32)

[INFO] training network...
Epoch 1/21


ValueError: ignored